### ISSUE TITLE
Animation on medals.

### ISSUE THREAD

**Issue by andrewkm** [xfrocks/bdMedal#3]
With BD Medals, animated medals are not animating on the profile page. Can you please check this out:

This is our medals page:
https://www.ecocitycraft.com/forum/help/medals

At the bottom the "Crate Master" medal is animated and works fine on that page, but in users profile:
https://www.ecocitycraft.com/forum/members/imabankthing.24679/

It is not animated.

Bottom right medal:
https://i.imgur.com/w7Vz811.png

Can you please help us with this?

PS: Sorry not sure where to post issues, here or the forums.

**Comment by daohoangson** [comment]
You may need to use the original size medal where you want medals to be animated. Otherwise the resized version will be used, and that version does not keep animations.

**Comment by andrewkm** [comment]
Looks like I had to upload the animated version to all three sections here:
https://i.imgur.com/Ih1oyPI.png

And it worked.

However, as you can see above, there is a fourth one (the very smallest one) that is not animated. How do I upload an image to the very small one as well?

All issues seem fixed other than that very smallest one :)

**Comment by daohoangson** [comment]
Ah, the tiny sized image (code `T`) does not support custom image. I think it is only used in AdminCP so you probably will have to leave it there.

**Comment by andrewkm** [comment]
Alright cool, I appreciate the help, thank you :)
